name: Deploy Firebase

on:
  push:
    branches: [main]
    paths:
      - firestore.rules
      - storage.rules
      - public/**
      - firebase.json

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Firestore rules, Storage rules & Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules,storage,hosting --project el-node-erp
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
